id: P008102
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG12160
  title: རྗེ་བཙུན་བྱམས་པ་མཐའ་ཡས་དཔལ་བཟང་པོའི་རྣམ་ཐར་དད་གསུམ་པད་ཚལ་རྒྱས་པའི་ཉིན་བྱེད།
  author: ''
  volumes:
    28c1ef61196d455a9517f7839c5afa51:
      image_group_id: I1KG12168
      title: Volume 1 of rje btsun byams pa mtha' yas dpal bzang po'i rnam thar dad
        gsum pad tshal rgyas pa'i nyin byed/
      volume_number: 1
      total_pages: 152
      base_file: v001.txt
