id: P008102
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12160
  title: རྗེ་བཙུན་བྱམས་པ་མཐའ་ཡས་དཔལ་བཟང་པོའི་རྣམ་ཐར་དད་གསུམ་པད་ཚལ་རྒྱས་པའི་ཉིན་བྱེད།
  author: ''
  volumes:
    053ce7c0b99043ffbc661d79d7391660:
      image_group_id: I1KG12168
      title: ''
      volume_number: 1
      total_pages: 152
ebook_metadata:
  title: རྗེ་བཙུན་བྱམས་པ་མཐའ་ཡས་དཔལ་བཟང་པོའི་རྣམ་ཐར་དད་གསུམ་པད་ཚལ་རྒྱས་པའི་ཉིན་བྱེད།
  author: ''
  sku: P008102
  cover: cover.jpg
  layers:
  - pagination
