id: IA26C2F23
legacy_id: P008102
ocr_import_info:
  bdrc_scan_id: W1KG12160
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T00:14:36'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:24:08.482219+00:00'
last_modified: 2022-08-31 11:24:15.528271
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG12160
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG12160
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྗེ་བཙུན་བྱམས་པ་མཐའ་ཡས་དཔལ་བཟང་པོའི་རྣམ་ཐར་དད་གསུམ་པད་ཚལ་རྒྱས་པའི་ཉིན་བྱེད།
  author: དགེ་བཤེས་བློ་བཟང་ཆོས་འབྱོར།
statistics:
  ocr_word_mean_confidence_index: 0.6716451562153833
  ocr_word_median_confidence_index: 0.7400000095367432
quality: null
bases:
  I1KG12168:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12168
      total_pages: 152
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12168.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.6716451562153833
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
