id: IA26C2F23
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T00:15:36+00:00'
last_modified: '2022-06-09T04:30:38.057282+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12160
  title: རྗེ་བཙུན་བྱམས་པ་མཐའ་ཡས་དཔལ་བཟང་པོའི་རྣམ་ཐར་དད་གསུམ་པད་ཚལ་རྒྱས་པའི་ཉིན་བྱེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    BF3B:
      image_group_id: I1KG12168
      title: Volume 1 of rje btsun byams pa mtha' yas dpal bzang po'i rnam thar dad
        gsum pad tshal rgyas pa'i nyin byed/
      total_pages: 152
      order: 1
      base_file: BF3B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
